---
- name: borrow/suche.feature
  scripts:
    cucumber:
      timeout: 600
      body: bundle exec cucumber -p default "features/borrow/suche.feature"
- name: borrow/vorlagen.feature
  scripts:
    cucumber:
      timeout: 600
      body: bundle exec cucumber -p default "features/borrow/vorlagen.feature"
- name: examples/pakete.feature
  scripts:
    cucumber:
      timeout: 600
      body: bundle exec cucumber -p default "features/examples/pakete.feature"
- name: manage/acknowledge/add_item.feature
  scripts:
    cucumber:
      timeout: 600
      body: bundle exec cucumber -p default "features/manage/acknowledge/add_item.feature"
