---
- name: Add the Iceweasel repository
  apt_repository: repo='deb http://mozilla.debian.net/ wheezy-backports iceweasel-release' state=present
  sudo: True
- name: Install Iceweasel
  apt: pkg=iceweasel state=installed update_cache=true
  sudo: True
- name: Install VNC server
  apt: pkg=tightvncserver state=installed update_cache=true
  sudo: True
- name: Install Fluxbox
  apt: pkg=fluxbox state=installed update_cache=true
  sudo: True
- name: Install xbase-clients
  apt: pkg=xbase-clients state=installed update_cache=true
  sudo: True
