default: -p base -e routes_report.rb
base:  -r features --tags=~@upcoming --format pretty --format rerun --out tmp/rerun.txt --tags=~@old-ui
rerun: "-r features @tmp/rerun.txt --format pretty --format rerun --out tmp/rererun.txt"
reports: -p base
