releases:

### CURRENT #######################################################################

- version_major: 4
  version_minor: 9
  version_patch: 0
  version_pre: 'RC.5'
  description: |

    database 37f691060..648007f5c:
      > Revert "Change user_name field to usage"
      > Change user_name field to usage

    legacy 039f234d2..54a9f96c4:
      > ci: fix meta check
      > Revert "Change user_name field to usage"
      > fix: add missing key to en_GB for attachment error
      > feature: add reactified categories filter to inventory list
      > feat: manage: search contracts by 'compact_id'
      > feature: reactify edit item
      > feature: reactify inventory list
      > ci: check-precompiled-assets
      > Display purpose on take back line
      > fix: lending: 'swap user' form submission in Safari
      > Change user_name field to usage
      > cider-ci: meta check for demo dump migration
      > fix: edit order link from failed approval modal

    zhdk-inventory dc188cd3e..48e15eed2:
      > configure db backups on staging


### HISTORY  ######################################################################

- version_major: 4
  version_minor: 8
  version_patch: 0
  version_pre: null
  description: |

    *lending*

    - feat: mark groups with too many assignments in red on group overview
    - fix: dont submit 'swap user' form when no user is selected
    - fix: hand over dialog autocomplete

    *procurement*

    - feat: admin can inspect in all categories
    - feat: only block nav for changed forms
    - feat: refresh button in overview
    - fix: Inspectors can see accounting fields of other categories
    - fix: only show budget limits if configured

    *database*

    - constraints for orders state and reject reason
    - add reject reason to orders
    - Remove purpose_id from orders

- version_major: 4
  version_minor: 7
  version_patch: 3
  version_pre: null
  description: |
    - Fix: Fix closed reservations contract state

- version_major: 4
  version_minor: 7
  version_patch: 2
  version_pre: null
  description: |
    - Fix: Redundant contracts in the list

- version_major: 4
  version_minor: 7
  version_patch: 1
  version_pre: null
  description: |
    - Fix: Button label for order line and group manager
    - Fix: Filter for verification required and order list
    - Fix: Reject button for orders with many items

- version_major: 4
  version_minor: 7
  version_patch: 0
  version_pre: null
  description: |
    - Feature: Disable flexible fields
    - Fix: Do not show location comma, if there is no location
    - Fix: Create item: save button i18n; date format; hide fields functionality
    - Fix: Show version for licenses on inventory
    - Fix: Inventory: edit Options, set inventory code as required
    - Technical: Orders & contracts refactoring
    - Locale: Admin inventory pool 18n

- version_major: 4
  version_minor: 6
  version_patch: 0
  version_pre: null
  description: |
    - Feature: inventory: add license version field
    - Feature: inventory: expert search
    - Feature: procurement: accounting type fields
    - Feature: procurement: inline edit request lines in overview
    - Feature: procurement: inspection comments templates
    - Feature: admin: show `languages` table
    - Feature: render app errors with details
    - Fix: Calendar and csv import translations
    - Fix: don't crash on inactive dynamic fields
    - Fix: inventory: enable quantity allocations for every license type
    - Fix: inventory: don't show "Undefined" types
    - Fix: inventory: don't show location for item-licenses
    - Fix: inventory: image upload restrictions error
    - Fix: lending: for order lines replace buttons dropdown with rejected label after rejection
    - Locale: Add French translation
    - Deploy: Support Debian 9 "stretch"

- version_major: 4
  version_minor: 5
  version_patch: 1
  version_pre: null
  description: |
    - Fix: Item.properties default hash
    - Fix: serialize User.settings
    - Fix: store -> serialize in item.rb
    - Fix: destroy in accept nested attributes
    - Fix: create fields rake task: inactive fields

- version_major: 4
  version_minor: 5
  version_patch: 0
  version_pre: null
  description: |
    - Fix: Fix create fields rake task: inactive fields
    - Fix: Fix access rights problems (fixes #283)
    - Fix: Patch image upload
    - Fix: perf: manage: inventory helper: limit autocompletes
    - Fix: Delete unsubmitted orders when deactivating pools (resolves #289)
    - Tech: Upgrade to Rails 5
    - Feat: Case insensitive take back

- version_major: 4
  version_minor: 4
  version_patch: 1
  version_pre: null
  description: |
    - Fix: Show item's location in hand over assign dropdown

- version_major: 4
  version_minor: 4
  version_patch: 0
  version_pre: null
  description: |
    - Feature: Search in audits (resolves #256)
    - Fix: Borrow: remove broken links from categories list (resolves #259)
    - Fix: Admin: search for user in admin tab only searches for admins (resolves #166)
    - Feature: Release page + deploy info
    - Feature: Add metadata to files & attachments (resolves #265)
    - Fix: Serial number validation warning in inventory helper (resolves #255)
    - Feature: Change contracts sorting in global search (resolves #242)
    - Documentation: Add owner_id & inventory_pool_id to items
    - Feature: New entity: Rooms (resolves #228)

- version_major: 4
  version_minor: 3
  version_patch: 1
  version_pre: null
  description: |

    ### Frontend Bug Fixes

    - Fix: BarcodeScanner: don't operate on focused inputs
    - Fix: upgrade tooltipster jquery plugin

- version_major: 4
  version_minor: 3
  version_patch: 0
  version_pre: null
  description: |

    - Feature: deactive pools (resolves #223)
    - Fix: Forbid first admin user if already exists
    - Fix: Inventory search in location's room (resolves #221)

- version_major: 4
  version_minor: 2
  version_patch: 0
  version_pre: null
  description: |

    ### Inventory Feature and Bug Fixing

    **Manage section**
    - When copying an item, the field "last checked" on the new item is set to the current date

    **Borrow section**
    - The information in the links **order**, **hand over** and **returns** on the top of the page show on the right hand side of the page the **date from** and **date to**. Before we showed the dates until or since as f.e. 1970 days since 23.7.2014.
    - The error messages on the top of the page when sending an order were not shown correctly.

- version_major: 4
  version_minor: 1
  version_patch: 0
  version_pre: null
  description: |

    ### Adjustments and Bug Fixing

    **Missing translations**
    - When submitting an order in the borrow section in the German part, the success message has now been translated to German.
    - Tab "return" in German part of leihs has now been translated to German

    **Borrow section**
    - The filter settings are not deleted anymore when switching from one category to another

    **Lending section**
    - Feature delegation contracts: When searching for a user, not only his own contracts are shown in the overview but also contracts of delegations, where this user is acting as borrower.
    - Bug fixing: Adding an item or model is not case sensitive anymore. This bug was introduced with the PostgreSQL-Update
    - Bug fixing: It is not possible to lend the same item at the same time to the same user.
    - Bug fixing: Date field when editing the calender in the return page was buggy. Now it is possible to delete the date or type a new date

    **Manage section**
    - Feature duplicate items: If you save an item where the serial-nr. already exists in leihs, you receive a warning asking, if you really want to save. This should help keep your inventory "tidy".

    **Admin section**
    - The shown time in the Audits-Page has been corrected to show the current time
    - The newest entries in the Audits-Page are now shown on the top

    **Installing leihs V4**
    - Enabling LDAP  in V4: How-to-documentation adjusted to enable LDAP under PostgreSQL
    - We now provide the possibility to create the first leihs-Admin-user through a UI
