jobs:

  hot_spot_scenarios:

    name: Hot Spot Scenarios

    description: |
      Manually run hot spot scenarios under MRI

    context:
      task_defaults:
        max_trials: 3
        include:
          - cider-ci_v4/task_components/database.yml
          - cider-ci_v4/task_components/precompile_assets.yml

      include:
        - cider-ci_v4/shared/main_context.yml
        - cider-ci/tasks/hot_spot_scenarios.yml
