jobs:

###

  MFA-prod:
    name: ⚒ Dev-Deploy [PROD-DATA] to mfa.ruby.zhdk.ch
    include: cider-ci/task-components/zhdk-dev-deploy-with-prod-data.yml
    context:
      task_defaults:
        exclusive_global_resources: { mfa.ruby.zhdk.ch: true }
        environment_variables:
          DEPLOY_TARGET_INVENTORY: 'developer-hosts --limit mfa'

  MFA-blank:
    name: ⚒ Dev-Deploy [BLANK] to mfa.ruby.zhdk.ch
    include: cider-ci/task-components/zhdk-dev-deploy-blank.yml
    context:
      task_defaults:
        exclusive_global_resources: { mfa.ruby.zhdk.ch: true }
        environment_variables:
          DEPLOY_TARGET_INVENTORY: 'developer-hosts --limit mfa'

###

  NIMAAI-prod:
    name: ⚒ Dev-Deploy [PROD-DATA] to nimaai.ruby.zhdk.ch
    include: cider-ci/task-components/zhdk-dev-deploy-with-prod-data.yml
    context:
      task_defaults:
        exclusive_global_resources: { nimaai.ruby.zhdk.ch: true }
        environment_variables:
          DEPLOY_TARGET_INVENTORY: 'developer-hosts --limit nimaai'

  NIMAAI-blank:
    name: ⚒ Dev-Deploy [BLANK] to nimaai.ruby.zhdk.ch
    include: cider-ci/task-components/zhdk-dev-deploy-blank.yml
    context:
      task_defaults:
        exclusive_global_resources: { nimaai.ruby.zhdk.ch: true }
        environment_variables:
          DEPLOY_TARGET_INVENTORY: 'developer-hosts --limit nimaai'

###

  PHIKU-prod:
    name: ⚒ Dev-Deploy [PROD-DATA] to phiku.ruby.zhdk.ch
    include: cider-ci/task-components/zhdk-dev-deploy-with-prod-data.yml
    context:
      task_defaults:
        exclusive_global_resources: { phiku.ruby.zhdk.ch: true }
        environment_variables:
          DEPLOY_TARGET_INVENTORY: 'developer-hosts --limit phiku'

  PHIKU-blank:
    name: ⚒ Dev-Deploy [BLANK] to phiku.ruby.zhdk.ch
    include: cider-ci/task-components/zhdk-dev-deploy-blank.yml
    context:
      task_defaults:
        exclusive_global_resources: { phiku.ruby.zhdk.ch: true }
        environment_variables:
          DEPLOY_TARGET_INVENTORY: 'developer-hosts --limit phiku'

###

  TOM-prod:
    name: ⚒ Dev-Deploy [PROD-DATA] to tom.ruby.zhdk.ch
    include: cider-ci/task-components/zhdk-dev-deploy-with-prod-data.yml
    context:
      task_defaults:
        exclusive_global_resources: { tom.ruby.zhdk.ch: true }
        environment_variables:
          DEPLOY_TARGET_INVENTORY: 'developer-hosts --limit tom'

  TOM-blank:
    name: ⚒ Dev-Deploy [BLANK] to tom.ruby.zhdk.ch
    include: cider-ci/task-components/zhdk-dev-deploy-blank.yml
    context:
      task_defaults:
        exclusive_global_resources: { tom.ruby.zhdk.ch: true }
        environment_variables:
          DEPLOY_TARGET_INVENTORY: 'developer-hosts --limit tom'

###

  v5-new-prod:
    name: ⚒ Dev-Deploy [PROD-DATA] to zhdk-leihs-prod-v5.ruby.zhdk.ch
    include: cider-ci/task-components/zhdk-dev-deploy-with-prod-data.yml
    context:
      task_defaults:
        exclusive_global_resources: { zhdk-leihs-prod-v5.ruby.zhdk.ch: true }
        environment_variables:
          DEPLOY_TARGET_INVENTORY: 'prod-hosts-v5'
          ANSIBLE_SSH_ARGS: '-i ~/.ssh/zhdk_ci_executor_rsa -o "UserKnownHostsFile ../zhdk-inventory/hosts-known-ssh-pubkeys"'

  v5-new-blank:
    name: ⚒ Dev-Deploy [BLANK] to zhdk-leihs-prod-v5.ruby.zhdk.ch
    include: cider-ci/task-components/zhdk-dev-deploy-blank.yml
    context:
      task_defaults:
        exclusive_global_resources: { zhdk-leihs-prod-v5.ruby.zhdk.ch: true }
        environment_variables:
          DEPLOY_TARGET_INVENTORY: 'prod-hosts-v5'
          ANSIBLE_SSH_ARGS: '-i ~/.ssh/zhdk_ci_executor_rsa -o "UserKnownHostsFile ../zhdk-inventory/hosts-known-ssh-pubkeys"'
