jobs:
  deploy-to-test:
    name: Deploy to leihs-v4-test.zhdk.ch
    priority: 2
    context:
      tasks:
        deploy:
          git_options:
            submodules:
              include_match: ^.*$
          exclusive_global_resources:
            "leihs-v4-test.zhdk.ch": true
          traits:
            g2016: true
          scripts:
            deploy:
              body: |
                set -eux
                cd deploy
                ansible-playbook deploy_play.yml \
                  --ssh-common-args '-i ~/.ssh/zhdk_ci_executor_rsa' \
                  -i ../zhdk-inventory/test-hosts
