jobs:
  deploy-to-zhdk-leihs-test:
    include: cider-ci/task-components/deploy-defaults.yml
    name: Deploy to zhdk-leihs-test.ruby.zhdk.ch
    context:

      task_defaults:
        exclusive_global_resources:
          "zhdk-leihs-test.ruby.zhdk.ch": true
        environment_variables:
          DEPLOY_TARGET_INVENTORY: test-hosts

      tasks:
        deploy:
          include: cider-ci/task-components/zhdk-test-deploy.yml
