jobs:
  test-container-deploy:
    include: cider-ci/task-components/container-deploy.yml

    name: Test Deploy to Container

    run_when:
      always:
        type: branch
        include_match: ^.*$
        exclude_match: '^.*no-ci.*$'

    context:

      task_defaults:
        traits: { lxd-on-zfs: yes }


      tasks:
        debian-stretch:
          name: Debian 9 (stretch)
          include: cider-ci/task-components/container-deploy/task-debian-9.yml
          scripts:
            cache-container:
              ignore_state: yes

        # # TMP: ignore, not ported yet. Needs Java 10 and possibly more
        # ubuntu-lts:
        #   name: Ubuntu 18.04 LTS
        #   include: cider-ci/task-components/container-deploy/task-ubuntu-1804.yml
        #   scripts:
        #     cache-container:
        #       ignore_state: yes
