jobs:
  test-container-deploy:
    name: Test Deploy to a Container
    run_when:
      'prototype for now':
        type: branch
        include_match: '^.*master.*$'
        exclude_match: '^.*no-ci.*$'
    context:
      include:
        - path: container-test/cider-ci/context.yml
          submodule: [deploy]


