jobs:

  MFA:
    name: ⚒ Dev-Deploy to mfa.ruby.zhdk.ch
    include: cider-ci/task-components/zhdk-dev-deploy.yml
    context:
      task_defaults:
        exclusive_global_resources: { mfa.ruby.zhdk.ch: true }
        environment_variables:
          DEPLOY_TARGET_INVENTORY: 'developer-hosts --limit mfa'


  NIMAAI:
    name: ⚒ Dev-Deploy to nimaai.ruby.zhdk.ch
    include: cider-ci/task-components/zhdk-dev-deploy.yml
    context:
      task_defaults:
        exclusive_global_resources: { nimaai.ruby.zhdk.ch: true }
        environment_variables:
          DEPLOY_TARGET_INVENTORY: 'developer-hosts --limit nimaai'


  PHIKU:
    name: ⚒ Dev-Deploy to phiku.ruby.zhdk.ch
    include: cider-ci/task-components/zhdk-dev-deploy.yml
    context:
      task_defaults:
        exclusive_global_resources: { phiku.ruby.zhdk.ch: true }
        environment_variables:
          DEPLOY_TARGET_INVENTORY: 'developer-hosts --limit phiku'


  TOM:
    name: ⚒ Dev-Deploy to tom.ruby.zhdk.ch
    include: cider-ci/task-components/zhdk-dev-deploy.yml
    context:
      task_defaults:
        exclusive_global_resources: { tom.ruby.zhdk.ch: true }
        environment_variables:
          DEPLOY_TARGET_INVENTORY: 'developer-hosts --limit tom'
