jobs:

  hot_spot_scenarios:

    name: Hot Spot Scenarios

    description: |
      Manually run hot spot scenarios under MRI

    context:
      task_defaults:
        max_trials: 3
        include:
          - cider-ci/task_components/database.yml

      include:
        - cider-ci/shared/main_context.yml
        - cider-ci/tasks/hot_spot_scenarios.yml
