jobs:

  leihs-admin-code-checks:

    name: Leihs Admin Code Checks

    description: |
      Run static checks and metrics: complexity, duplication, code format for Leihs Admin engine.

    run-on:
    - type: branch
      include-match: ^.*$

    context:

      _cider-ci_include:
        - cider-ci/shared/code-checks-context.yml

      tasks:

        lint_ruby:
          name: Lint/Stylecheck with Rubocop
          scripts:
            test:
              body: bundle exec rubocop engines/leihs_admin/ -c engines/leihs_admin/.rubocop.yml
