jobs:

  meta:

    name: Meta
    description: |
      Various superordinate quality assurance tasks

    run_when:
      always:
        type: branch
        include_match: ^.*$
        exclude_match: '^.*no-ci.*$'

    context:
      task_defaults:
        max_trials: 1
        traits:
          Ruby: true

      tasks:
        database-submodule-consistency:
          name: "database in toplevel and submodules all point to the same commit"
          scripts:
            main:
              body: |
                #!/usr/bin/env bash
                set -exu
                git fetch --all --quiet
                git submodule update --quiet --init --recursive

                v_top=$(git submodule status database | cut -f 2 -d ' ')
                v_legacy=$(git submodule status --recursive | grep legacy/database | cut -f 2 -d ' ')
                v_admin=$(git submodule status --recursive | grep admin/database | cut -f 2 -d ' ')
                v_procure=$(git submodule status --recursive | grep procure/server/database | cut -f 2 -d ' ')

                echo "toplevel: ${v_top}"
                echo "legacy:   ${v_legacy}"
                echo "admin:    ${v_admin}"
                echo "procure:  ${v_procure}"

                test $v_legacy == $v_top
                test $v_admin == $v_top
                test $v_procure == $v_top
