jobs:

  scenarios:

    name: Scenarios

    description: |
      Run leihs features (except engines) under MRI

    priority: -1

    run-on:
    - type: branch
      include-match: ^.*$

    context:
      task-defaults:
        max-auto-trials: 3

      _cider-ci_include:
        - cider-ci/shared/tests-context.yml
        - cider-ci/tasks/cucumber_scenarios.yml

